<?php

/**
 * Copyright © 2016-present Spryker Systems GmbH. All rights reserved.
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

declare(strict_types=1);

namespace Spryker\ApiPlatform\Command;

use SplFileInfo;
use Spryker\ApiPlatform\Configuration\ApiPlatformConfig;
use Spryker\ApiPlatform\Schema\Finder\SchemaFinderInterface;
use Spryker\ApiPlatform\Schema\Merger\SchemaMergerInterface;
use Spryker\ApiPlatform\Schema\Parser\SchemaParserInterface;
use Spryker\ApiPlatform\Schema\Report\CollectionInventoryBuilder;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

/**
 * Reports every list-shaped resource property and how well the published contract describes its
 * elements, so the fields still to adopt are a tracked work list rather than folklore.
 *
 * In `--check` mode it compares the freshly built report against the committed one and fails on any
 * difference. That covers both directions: a newly added untyped list shows up as an extra row, and a
 * property that silently became typed shows up as a changed row — either way the change has to be
 * committed, which puts it in front of a reviewer.
 */
class ApiCollectionsReportCommand extends Command
{
    protected const string NAME = 'api:collections:report';

    protected const int CODE_SUCCESS = 0;

    protected const int CODE_ERROR = 1;

    protected const string DEFAULT_OUTPUT_DIR = 'tests/api-contract';

    protected const string JSON_FILE_NAME = 'untyped-collections.json';

    protected const string MARKDOWN_FILE_NAME = 'untyped-collections.md';

    protected const string MARKDOWN_HEADER = <<<'MD'
        # Untyped collections

        Generated by `vendor/bin/glue api:collections:report`. Do not edit by hand.

        Every row below is the adoption backlog for typed nested collections, across every ApiType this
        run could see (Storefront and Backend), not a defect list. The mechanism that publishes a
        referenceable `items` schema for a list property exists and is proven end to end; nothing has
        adopted it on purpose yet, so existing responses stay byte-for-byte stable while adoption
        happens one property at a time. This report and its `--check` gate exist so that backlog is
        tracked and cannot silently regrow.

        Each row is a list-shaped property and how well the published contract describes its elements.
        `typed` and `canonical` publish a referenceable component schema; `handwritten` duplicates the
        shape in `openapiContext`; `example-only` and `unknown` publish nothing at all.

        Adopting a row means authoring `items` as a sibling of `type: array`. For an already-released
        property, first diff the real response payload's keys against the proposed `items.properties`:
        a typed element is a closed shape, so an incomplete block drops keys from the response.

        A `relationship` row is not adoptable at all: it is an `includes:` entry's auto-generated
        placeholder property, not an author-written collection. Adding `items` to it does not type
        anything — the relationship docblock wins the single available slot and `glue api:generate`
        rejects the change. It stays listed only so an `includes:` addition still shows up as drift.

        Backend coverage here reflects only the resource files this run's ApiType configuration did not
        hide. Some Backend modules (e.g. Store, Currency, Locale, StoreContext) are deliberately excluded
        from API Platform schema discovery entirely, on some or all of the real Glue applications, while
        their endpoints stay on the legacy Glue REST stack — their `resources/api/backend/*.resource.yml`
        files exist on disk but are invisible to this report until that exclusion is lifted.

        Resources under `vendor/` (e.g. `vendor/spryker-eco`) are out of scope by design: this is a
        backlog of adoption work for *this* repo, and a third-party package's schema is not something
        this repo can adopt. Excluding `vendor/` also keeps the baseline stable across CI lanes that
        resolve dependency versions differently (see `isVendorPath()`).

        MD;

    /**
     * @param iterable<\Spryker\ApiPlatform\Schema\Loader\SchemaLoaderInterface> $loaders
     */
    public function __construct(
        protected readonly SchemaFinderInterface $schemaFinder,
        protected readonly iterable $loaders,
        protected readonly SchemaParserInterface $schemaParser,
        protected readonly SchemaMergerInterface $schemaMerger,
        protected readonly ApiPlatformConfig $config,
        protected readonly CollectionInventoryBuilder $inventoryBuilder,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->setName(static::NAME)
            ->setDescription('Report list-shaped resource properties by contract fidelity')
            ->addOption(
                'output-dir',
                null,
                InputOption::VALUE_REQUIRED,
                'Directory the report artifacts are written to',
                static::DEFAULT_OUTPUT_DIR,
            )
            ->addOption(
                'check',
                null,
                InputOption::VALUE_NONE,
                'Compare against the committed report and fail on any difference; writes nothing',
            );
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $outputDir = (string)$input->getOption('output-dir');
        $rows = $this->collectRows();

        if ($input->getOption('check')) {
            return $this->check($io, $outputDir, $rows);
        }

        return $this->write($io, $outputDir, $rows);
    }

    /**
     * @return array<array{apiType: string, resource: string, property: string, state: string, itemKeyCount: int}>
     */
    protected function collectRows(): array
    {
        $rows = [];

        foreach ($this->discoverApiTypes() as $apiType) {
            foreach ($this->collectMergedSchemas($apiType) as $mergedSchema) {
                $rows = array_merge($rows, $this->inventoryBuilder->build($mergedSchema, $apiType));
            }
        }

        // Deterministic order: the JSON artifact is diffed byte-for-byte by --check, so an unstable
        // order would turn every unrelated run into a false failure.
        usort(
            $rows,
            static fn (array $left, array $right): int => [$left['apiType'], $left['resource'], $left['property']]
                <=> [$right['apiType'], $right['resource'], $right['property']],
        );

        return $rows;
    }

    /**
     * @return array<array<string, mixed>> One merged schema per resource of this ApiType.
     */
    protected function collectMergedSchemas(string $apiType): array
    {
        $parsedByResource = [];

        foreach ($this->schemaFinder->findSchemaFiles($apiType) as $file) {
            if ($this->isVendorPath((string)$file->getRealPath())) {
                continue;
            }

            $parsedSchema = $this->schemaParser->parse($this->loadSchema($file), $file);
            $resourceName = (string)($parsedSchema['name'] ?? '');

            if ($resourceName === '') {
                continue;
            }

            $parsedByResource[$resourceName][] = $parsedSchema;
        }

        $mergedSchemas = [];

        foreach ($parsedByResource as $resourceName => $schemas) {
            $mergedSchemas[] = $this->schemaMerger->merge($schemas, (string)$resourceName, $apiType);
        }

        return $mergedSchemas;
    }

    /**
     * @return array<string, mixed>
     */
    protected function loadSchema(SplFileInfo $file): array
    {
        foreach ($this->loaders as $loader) {
            if ($loader->supports($file)) {
                return $loader->load($file);
            }
        }

        return [];
    }

    /**
     * The inventory is a static read of schema YAML, not a runtime concern of the booted application,
     * so it must not stop at whichever ApiType the current kernel happens to be configured for. Returns
     * the union of the configured types and everything found on disk: returning the configured list
     * alone (as `ApiDebugCommand::discoverApiTypes()` does, where that is correct — a debug session is
     * about the one application you booted) would silently narrow this command's inventory, and
     * therefore its drift gate, to only the ApiType of whichever `GLUE_APPLICATION` booted the console,
     * hiding every other application's backlog with no signal that coverage had shrunk.
     *
     * Vendor source directories (e.g. `vendor/spryker-eco`) are skipped via {@see isVendorPath()} —
     * see that method's docblock for why.
     *
     * @return array<string>
     */
    protected function discoverApiTypes(): array
    {
        $apiTypes = $this->config->getApiTypes();

        foreach ($this->config->getSourceDirectories() as $sourceDir) {
            if ($this->isVendorPath($sourceDir)) {
                continue;
            }

            $matches = glob(sprintf('%s/*/resources/api', $sourceDir), GLOB_ONLYDIR);

            if ($matches === false) {
                continue;
            }

            foreach ($matches as $match) {
                $subDirs = glob(sprintf('%s/*', $match), GLOB_ONLYDIR);

                if ($subDirs === false) {
                    continue;
                }

                foreach ($subDirs as $subDir) {
                    // Disk directories under `resources/api/` also include non-resource specs, e.g.
                    // `asyncapi` (AsyncAPI channel/message documents such as `payment.yml`). Those are
                    // harmless to list here: `SchemaFinderInterface::findSchemaFiles()` only matches
                    // `*.resource.yaml`/`*.resource.yml`, so an ApiType directory that holds no such
                    // file (like `asyncapi`) naturally contributes zero rows rather than garbage.
                    $apiTypes[] = basename($subDir);
                }
            }
        }

        return array_values(array_unique($apiTypes));
    }

    /**
     * Whether `$path` has `vendor` as a path component (e.g. `.../vendor/spryker-eco/...`), never a
     * substring match — a directory legitimately named `myvendor` must not be excluded.
     *
     * `vendor/spryker-eco` is listed in `sourceDirectories` for schema discovery at runtime, but it is
     * gitignored and its contents vary with the resolved dependency versions. `scheduled.yml` runs one
     * CI lane on `dependency-versions: lowest` and another on the resolved-high lock, so a third-party
     * package's schema drifting between them would fail this command's `--check` gate with zero repo
     * changes, and no single committed baseline could satisfy both lanes at once. A committed baseline
     * must be a function of committed source, or it is unstable by construction — and a third-party
     * package's schema is not adoption work this repo can do, so its absence from the inventory is
     * correct rather than a coverage gap.
     */
    protected function isVendorPath(string $path): bool
    {
        return (bool)preg_match('#(?:^|/)vendor/#', str_replace('\\', '/', $path));
    }

    /**
     * @param array<array{apiType: string, resource: string, property: string, state: string, itemKeyCount: int}> $rows
     */
    protected function write(SymfonyStyle $io, string $outputDir, array $rows): int
    {
        if (!is_dir($outputDir) && !mkdir($outputDir, 0o777, true) && !is_dir($outputDir)) {
            $io->error(sprintf('Could not create output directory "%s".', $outputDir));

            return static::CODE_ERROR;
        }

        file_put_contents($outputDir . '/' . static::JSON_FILE_NAME, $this->renderJson($rows));
        file_put_contents($outputDir . '/' . static::MARKDOWN_FILE_NAME, $this->renderMarkdown($rows));

        $io->success(sprintf('Wrote %d list properties to %s.', count($rows), $outputDir));

        foreach ($this->countByState($rows) as $state => $count) {
            $io->writeln(sprintf('  %-13s %d', $state, $count));
        }

        return static::CODE_SUCCESS;
    }

    /**
     * @param array<array{apiType: string, resource: string, property: string, state: string, itemKeyCount: int}> $rows
     */
    protected function check(SymfonyStyle $io, string $outputDir, array $rows): int
    {
        $committedPath = $outputDir . '/' . static::JSON_FILE_NAME;

        if (!is_file($committedPath)) {
            $io->error(sprintf(
                'No committed report at %s. Run "vendor/bin/glue %s" and commit %s.',
                $committedPath,
                static::NAME,
                $outputDir,
            ));

            return static::CODE_ERROR;
        }

        $committed = json_decode((string)file_get_contents($committedPath), true);
        $committedRows = is_array($committed) && isset($committed['rows']) && is_array($committed['rows'])
            ? $committed['rows']
            : [];

        $added = $this->diffRows($rows, $committedRows);
        $removed = $this->diffRows($committedRows, $rows);

        if ($added === [] && $removed === []) {
            // Only once the rows agree: any row drift already implies markdown drift, and reporting
            // both would name two problems for one cause.
            return $this->checkMarkdown($io, $outputDir, $rows);
        }

        foreach ($added as $row) {
            $io->writeln(sprintf('<error>+ %s</error>', $this->describeRow($row)));
        }

        foreach ($removed as $row) {
            $io->writeln(sprintf('<comment>- %s</comment>', $this->describeRow($row)));
        }

        $io->error(sprintf(
            'The list-property inventory changed. Run "vendor/bin/glue %s" and commit %s.',
            static::NAME,
            $outputDir,
        ));

        return static::CODE_ERROR;
    }

    /**
     * The markdown is the artifact humans actually read, and {@see write()} always emits it alongside
     * the JSON — so a committed pair that disagrees means one of them was hand-edited or partially
     * committed. Diffing the rows alone would let that pass silently, leaving the readable half of the
     * report stale while the gate reported success.
     *
     * @param array<array{apiType: string, resource: string, property: string, state: string, itemKeyCount: int}> $rows
     */
    protected function checkMarkdown(SymfonyStyle $io, string $outputDir, array $rows): int
    {
        $committedPath = $outputDir . '/' . static::MARKDOWN_FILE_NAME;

        if (!is_file($committedPath)) {
            $io->error(sprintf(
                'No committed %s next to the report. Run "vendor/bin/glue %s" and commit %s.',
                static::MARKDOWN_FILE_NAME,
                static::NAME,
                $outputDir,
            ));

            return static::CODE_ERROR;
        }

        if (file_get_contents($committedPath) !== $this->renderMarkdown($rows)) {
            $io->error(sprintf(
                'The committed %s does not match the inventory. Run "vendor/bin/glue %s" and commit %s.',
                static::MARKDOWN_FILE_NAME,
                static::NAME,
                $outputDir,
            ));

            return static::CODE_ERROR;
        }

        $io->success(sprintf('List-property inventory is up to date (%d rows).', count($rows)));

        return static::CODE_SUCCESS;
    }

    /**
     * @param array<array<string, mixed>> $left
     * @param array<array<string, mixed>> $right
     *
     * @return array<array<string, mixed>>
     */
    protected function diffRows(array $left, array $right): array
    {
        $rightKeys = array_map(
            static fn (array $row): string => (string)json_encode($row),
            $right,
        );

        return array_values(array_filter(
            $left,
            static fn (array $row): bool => !in_array((string)json_encode($row), $rightKeys, true),
        ));
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function describeRow(array $row): string
    {
        return sprintf(
            '%s %s.%s [%s, %d keys]',
            $row['apiType'] ?? '?',
            $row['resource'] ?? '?',
            $row['property'] ?? '?',
            $row['state'] ?? '?',
            $row['itemKeyCount'] ?? 0,
        );
    }

    /**
     * @param array<array{apiType: string, resource: string, property: string, state: string, itemKeyCount: int}> $rows
     *
     * @return array<string, int>
     */
    protected function countByState(array $rows): array
    {
        $counts = [];

        foreach ($rows as $row) {
            $counts[$row['state']] = ($counts[$row['state']] ?? 0) + 1;
        }

        ksort($counts);

        return $counts;
    }

    /**
     * @param array<array{apiType: string, resource: string, property: string, state: string, itemKeyCount: int}> $rows
     */
    protected function renderJson(array $rows): string
    {
        return json_encode(['rows' => $rows], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
    }

    /**
     * @param array<array{apiType: string, resource: string, property: string, state: string, itemKeyCount: int}> $rows
     */
    protected function renderMarkdown(array $rows): string
    {
        $lines = [
            static::MARKDOWN_HEADER,
            '| API type | Resource | Property | State | Item keys |',
            '|---|---|---|---|--:|',
        ];

        foreach ($rows as $row) {
            $lines[] = sprintf(
                '| %s | %s | %s | %s | %d |',
                $row['apiType'],
                $row['resource'],
                $row['property'],
                $row['state'],
                $row['itemKeyCount'],
            );
        }

        return implode("\n", $lines) . "\n";
    }
}
